[build]
  publish = "dist" # Path to the built Vite app
  command = "npm run build" # Command to build the Vite app

[functions]
  directory = "netlify/functions" # Directory for your Netlify functions

[dev]
  functions = "netlify/functions" # Directory for local function development



